#!/usr/bin/env python3
"""Write the release evidence records from one Candidate Canary run.

Reads a successful run's redacted summaries (panel, lifecycle, hostile), refuses
unless every one binds the same candidate, passed, and scans clean, and only then
rewrites the records under ``docs/evidence/`` with the ``Release-*`` binding
that ``check_release_inputs.py`` validates. Results are generated; the only
hand-written part of a record is its **Operator notes** section.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from scan_evidence_leaks import scan

DEMO_ARTIFACTS = {
    "panel-github": "candidate-canary-github-summary",
    "panel-gitlab": "candidate-canary-gitlab-summary",
    "lifecycle-github": "candidate-canary-github-lifecycle-summary",
    "lifecycle-gitlab": "candidate-canary-gitlab-lifecycle-summary",
    "hostile-gitlab": "candidate-canary-gitlab-hostile-summary",
}
GENERATED_NOTE = (
    "> Generated by `scripts/canary_evidence_records.py` from the redacted summaries of\n"
    "> Candidate Canary run {run_id}. Do not edit the results by hand; regenerate them.\n"
    "> Add context only under **Operator notes**."
)


class RecordError(RuntimeError):
    pass


@dataclass(frozen=True)
class CanaryRun:
    run_id: str
    url: str
    date: str
    verify_candidate: str
    summaries: dict[str, dict[str, Any]]
    scanned_files: int


def _digest(image: str) -> str:
    return image.rsplit("@", 1)[1]


def _require_consistent(run: CanaryRun) -> dict[str, str]:
    if run.verify_candidate != "success":
        raise RecordError(f"verify-candidate concluded {run.verify_candidate}")
    if not run.summaries:
        raise RecordError("the run uploaded no canary summaries")
    candidates = {json.dumps(s["candidate"], sort_keys=True) for s in run.summaries.values()}
    if len(candidates) != 1:
        raise RecordError("the summaries do not bind one candidate")
    for key, summary in run.summaries.items():
        if key.startswith("panel-"):
            if summary.get("consensus", {}).get("status") == "incomplete":
                raise RecordError(f"{key} is incomplete")
            if summary.get("cleanup") != "success":
                raise RecordError(f"{key} cleanup was {summary.get('cleanup')}")
        elif summary.get("passed") is not True:
            raise RecordError(f"{key} did not pass")
    return next(iter(run.summaries.values()))["candidate"]


def _header(title: str, run: CanaryRun, candidate: dict[str, str]) -> list[str]:
    return [
        f"# Evidence record: {title} / {run.date}",
        "",
        "Status: passed",
        "",
        f"Release-runtime-source: {candidate['runtime_source']}",
        f"Release-base-digest: {_digest(candidate['base_image'])}",
        f"Release-reviewer-digest: {_digest(candidate['reviewer_image'])}",
        "",
        GENERATED_NOTE.format(run_id=f"[`{run.run_id}`]({run.url})"),
        "",
        "## Identity",
        "",
        f"- Runtime source `R`: `{candidate['runtime_source']}`",
        f"- Base image: `{candidate['base_image']}`",
        f"- Reviewer image: `{candidate['reviewer_image']}`",
        f"- Candidate Canary run: [`{run.run_id}`]({run.url}), {run.date}",
    ]


def _footer(run: CanaryRun, verdict: str) -> list[str]:
    return [
        "",
        "## Audit",
        "",
        f"- `scripts/scan_evidence_leaks.py` over all {run.scanned_files} downloaded summaries:"
        " no credential material. The summaries carry no model bodies by construction. An"
        " exact-value scan is not part of this record.",
        "",
        "## Operator notes",
        "",
        "None recorded.",
        "",
        "## Verdict",
        "",
        verdict,
        "",
    ]


def _table(rows: list[tuple[str, ...]], header: tuple[str, ...]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return lines


def canary_record(run: CanaryRun, candidate: dict[str, str]) -> str:
    rows = []
    for platform in ("github", "gitlab"):
        summary = run.summaries[f"panel-{platform}"]
        seats = summary["seats"]
        succeeded = sum(
            1
            for seat in seats.values()
            for stage in ("review", "critique")
            if seat[stage]["status"] == "success"
        )
        rows.append(
            (
                platform,
                f"[change]({summary['change_url']})",
                f"{succeeded}/{2 * len(seats)}",
                summary["consensus"]["panel_status"],
                ", ".join(summary["consensus"]["resolution_eligible_reviewers"]),
                str(summary["posting"]["posted_thread_count"]),
                summary["cleanup"],
            )
        )
    models = sorted(
        {
            f"{reviewer} `{seat['review'].get('model')}`"
            for platform in ("github", "gitlab")
            for reviewer, seat in run.summaries[f"panel-{platform}"]["seats"].items()
        }
    )
    lines = _header("Candidate Canary real four-seat panel", run, candidate)
    lines += [
        "",
        "## Image identity (`verify-candidate`)",
        "",
        f"`verify-candidate` concluded `{run.verify_candidate}`: both digests, OCI revision",
        "labels equal to `R`, reachability from protected `main`, and provenance attestations",
        "from the publish workflow were verified before any campaign ran.",
        "",
        "## Result",
        "",
        *_table(
            rows,
            ("Platform", "Change", "Stages", "Panel", "Resolution-eligible", "Threads", "Cleanup"),
        ),
        "",
        f"Models at the provider: {'; '.join(models)}.",
    ]
    lines += _footer(
        run,
        "Scoped pass. Against the frozen `R` and image pair, one real four-seat review and"
        " critique panel completed on each platform with every seat successful and"
        " resolution-eligible, a full panel, successful posting, and clean teardown.",
    )
    return "\n".join(lines)


def _step_rows(steps: list[dict[str, Any]]) -> list[tuple[str, ...]]:
    rows = []
    for step in steps:
        observed = step.get("observed", {})
        counts = ", ".join(
            f"{key}={observed[key]}"
            for key in (
                "status",
                "created_discussions",
                "updated_discussions",
                "resolved_discussions",
                "skipped_unchanged",
                "warnings",
                "mergeable",
                "mergeStateStatus",
                "detailed_merge_status",
            )
            if key in observed
        )
        rows.append((f"`{step['name']}`", "passed" if step["passed"] else "failed", counts))
    return rows


def lifecycle_record(run: CanaryRun, candidate: dict[str, str], platform: str) -> str:
    summary = run.summaries[f"lifecycle-{platform}"]
    name = {"github": "GitHub", "gitlab": "GitLab"}[platform]
    lines = _header(f"{name} / current-image lifecycle (mock Chain B)", run, candidate)
    lines += [
        f"- Change request: [change]({summary['change_url']}), temporary, closed at cleanup",
        "",
        "## Result",
        "",
        "Deterministic mock reviewer on every seat, zero tokens, driving the real platform",
        "posting, state, and command APIs on one finding identity. The fixture adds",
        "`src/audit.py`.",
        "",
        *_table(_step_rows(summary["steps"]), ("Step", "Result", "Observed")),
    ]
    lines += _footer(
        run,
        f"Scoped pass. On {name}, one mock finding identity on an added file went through"
        " every lifecycle step in the table, and a `blocker` thread left the change"
        " mergeable.",
    )
    return "\n".join(lines)


def hostile_record(run: CanaryRun, candidate: dict[str, str]) -> str:
    summary = run.summaries["hostile-gitlab"]
    rows = [
        (
            f"`{check['name']}`",
            "passed" if check["passed"] else "failed",
            json.dumps(check.get("observed", {}), sort_keys=True).replace("|", "\\|"),
        )
        for check in summary["steps"]
    ]
    lines = _header("GitLab hostile-MR deployment boundary", run, candidate)
    lines += [
        f"- Change request: [change]({summary['change_url']}) from an **unprotected** branch,"
        " closed at cleanup",
        "",
        "## Result",
        "",
        *_table(rows, ("Check", "Result", "Observed")),
        "",
        "`image_substituted` is recorded, not asserted: in-pipeline image enforcement is not",
        "implemented (SPEC-43), so containment rests on credential withholding and the",
        "out-of-band trust auditor.",
    ]
    lines += _footer(
        run,
        "Scoped pass for the recorded boundary. An MR from an unprotected ref could not obtain"
        " any protected credential, prepare failed closed with every later stage skipped, the"
        " forged publication artifacts went unconsumed, and the trust auditor rejected the"
        ' hostile composition. "Credential isolated" holds only in this hardened-child,'
        " unprotected-ref sense.",
    )
    return "\n".join(lines)


RECORDS: dict[str, tuple[tuple[str, ...], Callable[[CanaryRun, dict[str, str]], str]]] = {
    "record-candidate-canary.md": (("panel-github", "panel-gitlab"), canary_record),
    "record-github-current-image.md": (
        ("lifecycle-github",),
        lambda run, candidate: lifecycle_record(run, candidate, "github"),
    ),
    "record-gitlab-current-image.md": (
        ("lifecycle-gitlab",),
        lambda run, candidate: lifecycle_record(run, candidate, "gitlab"),
    ),
    "record-gitlab-hostile-mr.md": (("hostile-gitlab",), hostile_record),
}


def render_records(run: CanaryRun) -> dict[str, str]:
    """Return every record whose summaries the run produced."""
    candidate = _require_consistent(run)
    return {
        filename: render(run, candidate)
        for filename, (needs, render) in RECORDS.items()
        if all(key in run.summaries for key in needs)
    }


def _gh(*args: str) -> str:
    completed = subprocess.run(["gh", *args], text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise RecordError(completed.stderr.strip() or f"gh {args[0]} failed")
    return completed.stdout


def load_run(run_id: str, workdir: Path) -> CanaryRun:
    meta = json.loads(_gh("run", "view", run_id, "--json", "url,createdAt,conclusion,jobs"))
    conclusion = meta.get("conclusion")
    if conclusion != "success":
        raise RecordError(
            f"Candidate Canary run {run_id} concluded {conclusion!r}; expected success"
        )
    verify = next(
        (job["conclusion"] for job in meta["jobs"] if job["name"] == "verify-candidate"),
        "missing",
    )
    _gh("run", "download", run_id, "--dir", str(workdir))
    summaries = {}
    for key, artifact in DEMO_ARTIFACTS.items():
        files = list((workdir / artifact).glob("*.json"))
        if len(files) == 1:
            summaries[key] = json.loads(files[0].read_text(encoding="utf-8"))
    findings, scanned, _ = scan([workdir])
    if findings:
        raise RecordError(f"the leak scan flagged the summaries: {sorted(findings)}")
    return CanaryRun(
        run_id=run_id,
        url=meta["url"],
        date=meta["createdAt"][:10],
        verify_candidate=str(verify),
        summaries=summaries,
        scanned_files=scanned,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run_id", help="Candidate Canary workflow run ID")
    parser.add_argument("--out", type=Path, default=Path("docs/evidence"))
    args = parser.parse_args(argv)
    try:
        with tempfile.TemporaryDirectory() as tmp:
            records = render_records(load_run(args.run_id, Path(tmp)))
    except RecordError as exc:
        print(f"ERROR: {exc}")
        return 1
    for filename, text in records.items():
        (args.out / filename).write_text(text, encoding="utf-8")
        print(f"wrote {args.out / filename}")
    missing = sorted(set(RECORDS) - set(records))
    for filename in missing:
        print(f"skipped {filename}: the run did not include its campaign")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
