#!/usr/bin/env python3
"""Write the release evidence records from one Candidate Canary run.

Reads a successful run's redacted summaries (panel, lifecycle, hostile), refuses
unless every one binds the same candidate, passed, and scans clean, and only then
rewrites the records under ``docs/evidence/`` with the ``Release-*`` binding
that ``check_release_inputs.py`` validates. Results are generated; the only
hand-written part of a record is its **Operator notes** section.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from functools import partial
from pathlib import Path
from typing import Any

from candidate_canary_common import LIFECYCLE_FIXTURE_PATH, POST_COUNT_KEYS
from check_release_inputs import EVIDENCE_DIR
from release_common import DIGEST_RE, ROOT
from scan_evidence_leaks import scan
from validate_candidate_identity import REPOSITORY, SOURCE_REF


@dataclass(frozen=True)
class CanaryArtifact:
    name: str
    job: str
    platform: str


DEMO_ARTIFACTS = {
    "panel-github": CanaryArtifact("candidate-canary-github-summary", "campaign", "github"),
    "panel-gitlab": CanaryArtifact("candidate-canary-gitlab-summary", "campaign", "gitlab"),
    "lifecycle-github": CanaryArtifact(
        "candidate-canary-github-lifecycle-summary", "lifecycle", "github"
    ),
    "lifecycle-gitlab": CanaryArtifact(
        "candidate-canary-gitlab-lifecycle-summary", "lifecycle", "gitlab"
    ),
    "hostile-gitlab": CanaryArtifact(
        "candidate-canary-gitlab-hostile-summary", "hostile", "gitlab"
    ),
}
CANARY_WORKFLOW = ".github/workflows/candidate-canary.yml"
RUN_FIELDS = "url,createdAt,status,conclusion,event,headBranch,workflowDatabaseId,jobs"
LIFECYCLE_OBSERVED_KEYS = (
    "run_id",
    "persist_run_id",
    "pipeline",
    "persist_pipeline",
    "thread",
    *POST_COUNT_KEYS,
    "mergeable",
    "mergeStateStatus",
    "detailed_merge_status",
    "state",
    "persisted_state",
    "persisted",
)


class RecordError(RuntimeError):
    pass


@dataclass(frozen=True)
class CanaryRun:
    run_id: str
    url: str
    date: str
    summaries: dict[str, dict[str, Any]]
    expected_summaries: frozenset[str]
    scanned_files: int


def _digest(image: str) -> str:
    digest = image.rpartition("@")[2]
    if DIGEST_RE.fullmatch(digest) is None:
        raise RecordError(f"{image!r} is not a digest-pinned image reference")
    return digest


def _require_consistent(run: CanaryRun) -> dict[str, str]:
    missing = run.expected_summaries - run.summaries.keys()
    unexpected = run.summaries.keys() - run.expected_summaries
    if missing or unexpected:
        raise RecordError(
            f"campaign summaries disagree with job metadata: "
            f"missing={sorted(missing)}, unexpected={sorted(unexpected)}"
        )
    if not run.summaries:
        raise RecordError("the run uploaded no canary summaries")
    candidates = {json.dumps(s["candidate"], sort_keys=True) for s in run.summaries.values()}
    if len(candidates) != 1:
        raise RecordError("the summaries do not bind one candidate")
    for key, summary in run.summaries.items():
        if key.startswith("panel-"):
            if summary.get("consensus", {}).get("status") == "incomplete":
                raise RecordError(f"{key} is incomplete")
            if summary.get("cleanup") != "success":
                raise RecordError(f"{key} cleanup was {summary.get('cleanup')}")
        elif summary.get("passed") is not True:
            raise RecordError(f"{key} did not pass")
    return next(iter(run.summaries.values()))["candidate"]


def _header(title: str, run: CanaryRun, candidate: dict[str, str]) -> list[str]:
    return [
        f"# Evidence record: {title} / {run.date}",
        "",
        "Status: passed",
        "",
        f"Release-runtime-source: {candidate['runtime_source']}",
        f"Release-base-digest: {_digest(candidate['base_image'])}",
        f"Release-reviewer-digest: {_digest(candidate['reviewer_image'])}",
        "",
        "> Generated by `scripts/canary_evidence_records.py` from the redacted summaries of",
        f"> Candidate Canary run [`{run.run_id}`]({run.url}). Do not edit the results by hand;",
        "> regenerate them. Add context only under **Operator notes**.",
        "",
        "## Identity",
        "",
        f"- Runtime source `R`: `{candidate['runtime_source']}`",
        f"- Base image: `{candidate['base_image']}`",
        f"- Reviewer image: `{candidate['reviewer_image']}`",
        f"- Candidate Canary run: [`{run.run_id}`]({run.url}), {run.date}",
    ]


def _footer(run: CanaryRun, verdict: str) -> list[str]:
    return [
        "",
        "## Audit",
        "",
        f"- `scripts/scan_evidence_leaks.py` over all {run.scanned_files} downloaded summaries:"
        " no credential material. The summaries carry no model bodies by construction. An"
        " exact-value scan is not part of this record.",
        "",
        "## Operator notes",
        "",
        "None recorded.",
        "",
        "## Verdict",
        "",
        verdict,
        "",
    ]


def _table(rows: list[tuple[str, ...]], header: tuple[str, ...]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(cell.replace("|", "\\|") for cell in row) + " |" for row in rows]
    return lines


def canary_record(run: CanaryRun, candidate: dict[str, str]) -> str:
    rows = []
    models = set()
    for platform in ("github", "gitlab"):
        summary = run.summaries[f"panel-{platform}"]
        seats = summary["seats"]
        models |= {
            f"{reviewer} `{seat['review'].get('model')}`" for reviewer, seat in seats.items()
        }
        succeeded = sum(
            1
            for seat in seats.values()
            for stage in ("review", "critique")
            if seat[stage]["status"] == "success"
        )
        rows.append(
            (
                platform,
                f"[change]({summary['change_url']})",
                f"{succeeded}/{2 * len(seats)}",
                summary["consensus"]["panel_status"],
                ", ".join(summary["consensus"]["resolution_eligible_reviewers"]),
                str(summary["posting"]["posted_thread_count"]),
                summary["cleanup"],
            )
        )
    lines = _header("Candidate Canary real four-seat panel", run, candidate)
    lines += [
        "",
        "## Image identity (`verify-candidate`)",
        "",
        "`verify-candidate` concluded `success`: both digests, OCI revision",
        "labels equal to `R`, reachability from protected `main`, and provenance attestations",
        "from the publish workflow were verified before any campaign ran.",
        "",
        "## Result",
        "",
        *_table(
            rows,
            ("Platform", "Change", "Stages", "Panel", "Resolution-eligible", "Threads", "Cleanup"),
        ),
        "",
        f"Models at the provider: {'; '.join(sorted(models))}.",
    ]
    lines += _footer(
        run,
        "Scoped pass. Against the frozen `R` and image pair, one real four-seat review and"
        " critique panel completed on each platform with every seat successful and"
        " resolution-eligible, a full panel, successful posting, and clean teardown.",
    )
    return "\n".join(lines)


def _step_rows(
    steps: list[dict[str, Any]], observed: Callable[[dict[str, Any]], str]
) -> list[tuple[str, ...]]:
    return [
        (
            f"`{step['name']}`",
            "passed" if step["passed"] else "failed",
            observed(step.get("observed", {})),
        )
        for step in steps
    ]


def _lifecycle_counts(observed: dict[str, Any]) -> str:
    values = []
    for key in LIFECYCLE_OBSERVED_KEYS:
        if key in observed:
            value = observed[key]
            values.append(f"{key}={_observed_json(value) if isinstance(value, dict) else value}")
    return ", ".join(values)


def _observed_json(observed: dict[str, Any]) -> str:
    return json.dumps(observed, sort_keys=True)


def lifecycle_record(run: CanaryRun, candidate: dict[str, str], platform: str) -> str:
    summary = run.summaries[f"lifecycle-{platform}"]
    name = {"github": "GitHub", "gitlab": "GitLab"}[platform]
    lines = _header(f"{name} / current-image lifecycle (mock Chain B)", run, candidate)
    lines += [
        f"- Change request: [change]({summary['change_url']}), temporary, closed at cleanup",
        "",
        "## Result",
        "",
        "Deterministic mock reviewer on every seat, zero tokens, driving the real platform",
        "posting, state, and command APIs on one finding identity. The fixture adds",
        f"`{LIFECYCLE_FIXTURE_PATH}`.",
        "",
        *_table(_step_rows(summary["steps"], _lifecycle_counts), ("Step", "Result", "Observed")),
    ]
    lines += _footer(
        run,
        f"Scoped pass. On {name}, one mock finding identity on an added file went through"
        " every lifecycle step in the table, and a `blocker` thread left the change"
        " mergeable.",
    )
    return "\n".join(lines)


def hostile_record(run: CanaryRun, candidate: dict[str, str]) -> str:
    summary = run.summaries["hostile-gitlab"]
    lines = _header("GitLab hostile-MR deployment boundary", run, candidate)
    lines += [
        f"- Change request: [change]({summary['change_url']}) from an **unprotected** branch,"
        " closed at cleanup",
        "",
        "## Result",
        "",
        *_table(_step_rows(summary["steps"], _observed_json), ("Check", "Result", "Observed")),
        "",
        "`image_substituted` is recorded, not asserted: in-pipeline image enforcement is not",
        "implemented (SPEC-43), so containment rests on credential withholding and the",
        "out-of-band trust auditor.",
    ]
    lines += _footer(
        run,
        "Scoped pass for the recorded boundary. An MR from an unprotected ref could not obtain"
        " any protected credential, prepare failed closed with every later stage skipped, the"
        " forged publication artifacts went unconsumed, and the trust auditor rejected the"
        ' hostile composition. "Credential isolated" holds only in this hardened-child,'
        " unprotected-ref sense.",
    )
    return "\n".join(lines)


RECORDS: dict[str, tuple[tuple[str, ...], Callable[[CanaryRun, dict[str, str]], str]]] = {
    "record-candidate-canary.md": (("panel-github", "panel-gitlab"), canary_record),
    "record-github-current-image.md": (
        ("lifecycle-github",),
        partial(lifecycle_record, platform="github"),
    ),
    "record-gitlab-current-image.md": (
        ("lifecycle-gitlab",),
        partial(lifecycle_record, platform="gitlab"),
    ),
    "record-gitlab-hostile-mr.md": (("hostile-gitlab",), hostile_record),
}


def render_records(run: CanaryRun) -> dict[str, str]:
    """Render complete evidence for the campaigns confirmed by job metadata."""
    try:
        candidate = _require_consistent(run)
        return {
            filename: render(run, candidate)
            for filename, (needs, render) in RECORDS.items()
            if all(key in run.expected_summaries for key in needs)
        }
    except (KeyError, TypeError, AttributeError) as exc:
        raise RecordError(f"invalid canary summary data: {exc}") from exc


def _gh(*args: str) -> str:
    completed = subprocess.run(["gh", *args], text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise RecordError(completed.stderr.strip() or f"gh {args[0]} failed")
    return completed.stdout


def _json_object(text: str, label: str) -> dict[str, Any]:
    try:
        value = json.loads(text)
    except json.JSONDecodeError as exc:
        raise RecordError(f"{label} is not valid JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise RecordError(f"{label} must be a JSON object")
    return value


def _successful_job(job: dict[str, Any]) -> None:
    if job.get("status") != "completed" or job.get("conclusion") != "success":
        raise RecordError(
            f"{job['name']} has status {job.get('status')!r}, "
            f"concluded {job.get('conclusion')!r}; expected completed success"
        )


def _expected_summaries(jobs: list[dict[str, Any]]) -> frozenset[str]:
    expected = set()
    for family in dict.fromkeys(artifact.job for artifact in DEMO_ARTIFACTS.values()):
        artifacts = {key: spec for key, spec in DEMO_ARTIFACTS.items() if spec.job == family}
        family_jobs = [
            job for job in jobs if job["name"] == family or job["name"].startswith(f"{family} (")
        ]
        # GitHub evaluates the campaign condition before expanding its matrix.
        if (
            len(family_jobs) == 1
            and family_jobs[0]["name"] == family
            and family_jobs[0].get("status") == "completed"
            and family_jobs[0].get("conclusion") == "skipped"
        ):
            continue
        if len(family_jobs) != len(artifacts):
            raise RecordError(f"{family} job metadata is missing or ambiguous")
        for key, artifact in artifacts.items():
            pattern = (
                family
                if len(artifacts) == 1
                else rf"{family} \({artifact.platform}(?:, [^()]+)?\)"
            )
            matches = [
                job for job in family_jobs if re.fullmatch(pattern, job["name"])
            ]
            if len(matches) != 1:
                raise RecordError(f"{key} job metadata is missing or ambiguous")
            _successful_job(matches[0])
            expected.add(key)
    if not expected:
        raise RecordError("the run included no successful canary campaigns")
    return frozenset(expected)


def load_run(run_id: str, workdir: Path) -> CanaryRun:
    repository = f"github.com/{REPOSITORY}"
    meta = _json_object(
        _gh("run", "view", run_id, "--repo", repository, "--json", RUN_FIELDS), "run metadata"
    )
    conclusion = meta.get("conclusion")
    if conclusion != "success":
        raise RecordError(
            f"Candidate Canary run {run_id} concluded {conclusion!r}; expected success"
        )
    required = {
        "status": "completed",
        "event": "workflow_dispatch",
        "headBranch": SOURCE_REF.removeprefix("refs/heads/"),
    }
    for field, value in required.items():
        if meta.get(field) != value:
            raise RecordError(f"run {run_id} {field} is {meta.get(field)!r}; expected {value!r}")
    for field in ("url", "createdAt"):
        if not isinstance(meta.get(field), str) or not meta[field]:
            raise RecordError(f"run metadata is missing {field}")
    workflow_id = meta.get("workflowDatabaseId")
    if type(workflow_id) is not int or workflow_id <= 0:
        raise RecordError("run metadata is missing a valid workflowDatabaseId")
    workflow = _json_object(
        _gh(
            "api", "--hostname", "github.com", f"repos/{REPOSITORY}/actions/workflows/{workflow_id}"
        ),
        "workflow metadata",
    )
    if workflow.get("id") != workflow_id or workflow.get("path") != CANARY_WORKFLOW:
        raise RecordError(f"run {run_id} is not the canonical {CANARY_WORKFLOW} workflow")
    jobs = meta.get("jobs")
    if not isinstance(jobs, list) or not all(
        isinstance(job, dict) and isinstance(job.get("name"), str) for job in jobs
    ):
        raise RecordError("run metadata is missing a valid jobs list")
    verify = [job for job in jobs if job["name"] == "verify-candidate"]
    if len(verify) != 1:
        raise RecordError("verify-candidate job metadata is missing or ambiguous")
    _successful_job(verify[0])
    expected = _expected_summaries(jobs)
    _gh("run", "download", run_id, "--repo", repository, "--dir", str(workdir))
    summaries = {}
    for key, artifact in DEMO_ARTIFACTS.items():
        directory = workdir / artifact.name
        if key not in expected:
            if directory.exists():
                raise RecordError(f"{key} uploaded an artifact despite its campaign being skipped")
            continue
        files = list(directory.glob("*.json"))
        if len(files) != 1 or not files[0].is_file():
            raise RecordError(f"{key} requires exactly one summary JSON file; found {len(files)}")
        try:
            summaries[key] = _json_object(files[0].read_text(encoding="utf-8"), f"{key} summary")
        except (OSError, UnicodeError) as exc:
            raise RecordError(f"cannot read {key} summary: {exc}") from exc
    findings, scanned, _ = scan([workdir])
    if findings:
        raise RecordError(f"the leak scan flagged the summaries: {sorted(findings)}")
    return CanaryRun(
        run_id=run_id,
        url=meta["url"],
        date=meta["createdAt"][:10],
        summaries=summaries,
        expected_summaries=expected,
        scanned_files=scanned,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run_id", help="Candidate Canary workflow run ID")
    parser.add_argument("--out", type=Path, default=ROOT / EVIDENCE_DIR)
    args = parser.parse_args(argv)
    try:
        with tempfile.TemporaryDirectory() as tmp:
            records = render_records(load_run(args.run_id, Path(tmp)))
    except RecordError as exc:
        print(f"ERROR: {exc}")
        return 1
    for filename, text in records.items():
        (args.out / filename).write_text(text, encoding="utf-8")
        print(f"wrote {args.out / filename}")
    missing = sorted(set(RECORDS) - set(records))
    for filename in missing:
        print(f"skipped {filename}: the run did not include its campaign")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
