"""Load, validate, and render evidence from one Candidate Canary run.

Reads a successful run's redacted summaries (panel, lifecycle, hostile), refuses
unless every one binds the same candidate, passed, and scans clean, and only then
renders records with the ``Release-*`` bindings that ``check_release_inputs.py``
validates. Release preparation owns writes; this module preserves matching
records' handwritten **Operator notes** sections.
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable
from dataclasses import dataclass
from functools import partial
from pathlib import Path
from typing import Any

import release_common
from ai_review.canonical import json_loads_no_duplicates
from candidate_canary_common import LIFECYCLE_FIXTURE_PATH
from check_release_inputs import release_bindings
from release_common import DIGEST_RE
from scan_evidence_leaks import scan
from validate_candidate_identity import REPOSITORY, SOURCE_REF


@dataclass(frozen=True)
class CanaryArtifact:
    name: str
    job: str


DEMO_ARTIFACTS = {
    "panel-github": CanaryArtifact("candidate-canary-github-summary", "campaign"),
    "panel-gitlab": CanaryArtifact("candidate-canary-gitlab-summary", "campaign"),
    "lifecycle-github": CanaryArtifact("candidate-canary-github-lifecycle-summary", "lifecycle"),
    "lifecycle-gitlab": CanaryArtifact("candidate-canary-gitlab-lifecycle-summary", "lifecycle"),
    "hostile-gitlab": CanaryArtifact("candidate-canary-gitlab-hostile-summary", "hostile"),
}
CANARY_WORKFLOW = ".github/workflows/candidate-canary.yml"
RUN_FIELDS = "url,createdAt,status,conclusion,event,headBranch,workflowDatabaseId,jobs"


class RecordError(RuntimeError):
    pass


@dataclass(frozen=True)
class CanaryRun:
    run_id: str
    url: str
    date: str
    summaries: dict[str, dict[str, Any]]
    scanned_files: int


def _digest(image: str) -> str:
    digest = image.rpartition("@")[2]
    if DIGEST_RE.fullmatch(digest) is None:
        raise RecordError(f"{image!r} is not a digest-pinned image reference")
    return digest


def _require_consistent(run: CanaryRun) -> dict[str, str]:
    candidates = {json.dumps(s["candidate"], sort_keys=True) for s in run.summaries.values()}
    if len(candidates) != 1:
        raise RecordError("the summaries do not bind one candidate")
    for key, summary in run.summaries.items():
        if key.startswith("panel-"):
            if summary.get("consensus", {}).get("status") == "incomplete":
                raise RecordError(f"{key} is incomplete")
            if summary.get("cleanup") != "success":
                raise RecordError(f"{key} cleanup was {summary.get('cleanup')}")
        elif summary.get("passed") is not True:
            raise RecordError(f"{key} did not pass")
    return next(iter(run.summaries.values()))["candidate"]


def _header(title: str, run: CanaryRun, candidate: dict[str, str]) -> list[str]:
    return [
        f"# Evidence record: {title} / {run.date}",
        "",
        "Status: passed",
        "",
        f"Release-runtime-source: {candidate['runtime_source']}",
        f"Release-base-digest: {_digest(candidate['base_image'])}",
        f"Release-reviewer-digest: {_digest(candidate['reviewer_image'])}",
        "",
        "> Generated by `scripts/canary_evidence_records.py` from the redacted summaries of",
        "> the Candidate Canary run below. Do not edit the results by hand; regenerate them.",
        "> Add context only under **Operator notes**.",
        "",
        "## Identity",
        "",
        f"- Runtime source `R`: `{candidate['runtime_source']}`",
        f"- Base image: `{candidate['base_image']}`",
        f"- Reviewer image: `{candidate['reviewer_image']}`",
        f"- Candidate Canary run: [`{run.run_id}`]({run.url}), {run.date}",
    ]


def _footer(run: CanaryRun, verdict: str) -> list[str]:
    return [
        "",
        "## Audit",
        "",
        f"- `scripts/scan_evidence_leaks.py` over all {run.scanned_files} downloaded summaries:"
        " no credential material. The summaries carry no model bodies by construction. An"
        " exact-value scan is not part of this record.",
        "",
        "## Operator notes",
        "",
        "None recorded.",
        "",
        "## Verdict",
        "",
        verdict,
        "",
    ]


def _table(rows: list[tuple[str, ...]], header: tuple[str, ...]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(cell.replace("|", "\\|") for cell in row) + " |" for row in rows]
    return lines


def canary_record(run: CanaryRun, candidate: dict[str, str]) -> str:
    rows = []
    models = set()
    for platform in ("github", "gitlab"):
        summary = run.summaries[f"panel-{platform}"]
        seats = summary["seats"]
        models |= {
            f"{reviewer} `{seat['review'].get('model')}`" for reviewer, seat in seats.items()
        }
        succeeded = sum(
            1
            for seat in seats.values()
            for stage in ("review", "critique")
            if seat[stage]["status"] == "success"
        )
        rows.append(
            (
                platform,
                f"[change]({summary['change_url']})",
                f"{succeeded}/{2 * len(seats)}",
                summary["consensus"]["panel_status"],
                ", ".join(summary["consensus"]["resolution_eligible_reviewers"]),
                str(summary["posting"]["posted_thread_count"]),
                summary["cleanup"],
            )
        )
    lines = _header("Candidate Canary real four-seat panel", run, candidate)
    lines += [
        "",
        "## Image identity (`verify-candidate`)",
        "",
        "`verify-candidate` concluded `success`: both digests, OCI revision",
        "labels equal to `R`, reachability from protected `main`, and provenance attestations",
        "from the publish workflow were verified before any campaign ran.",
        "",
        "## Result",
        "",
        *_table(
            rows,
            ("Platform", "Change", "Stages", "Panel", "Resolution-eligible", "Threads", "Cleanup"),
        ),
        "",
        f"Models at the provider: {'; '.join(sorted(models))}.",
    ]
    lines += _footer(
        run,
        "Scoped pass. Against the frozen `R` and image pair, one real four-seat review and"
        " critique panel completed on each platform with every seat successful and"
        " resolution-eligible, a full panel, successful posting, and clean teardown.",
    )
    return "\n".join(lines)


def _step_rows(
    steps: list[dict[str, Any]], observed: Callable[[dict[str, Any]], str]
) -> list[tuple[str, ...]]:
    return [
        (
            f"`{step['name']}`",
            "passed" if step["passed"] else "failed",
            observed(step.get("observed", {})),
        )
        for step in steps
    ]


def _observed_json(observed: dict[str, Any]) -> str:
    return json.dumps(observed, sort_keys=True)


def _lifecycle_observed(observed: dict[str, Any]) -> str:
    return ", ".join(
        f"{key}={_observed_json(value) if isinstance(value, dict) else value}"
        for key, value in observed.items()
        # Per-reviewer results are already summarized by the panel record.
        if key != "reviewers"
    )


def lifecycle_record(run: CanaryRun, candidate: dict[str, str], platform: str) -> str:
    summary = run.summaries[f"lifecycle-{platform}"]
    name = {"github": "GitHub", "gitlab": "GitLab"}[platform]
    lines = _header(f"{name} / current-image lifecycle (mock Chain B)", run, candidate)
    lines += [
        f"- Change request: [change]({summary['change_url']}), temporary, closed at cleanup",
        "",
        "## Result",
        "",
        "Deterministic mock reviewer on every seat, zero tokens, driving the real platform",
        "posting, state, and command APIs on one finding identity. The fixture adds",
        f"`{LIFECYCLE_FIXTURE_PATH}`.",
        "",
        *_table(_step_rows(summary["steps"], _lifecycle_observed), ("Step", "Result", "Observed")),
    ]
    lines += _footer(
        run,
        f"Scoped pass. On {name}, one mock finding identity on an added file went through"
        " every lifecycle step in the table, and a `blocker` thread left the change"
        " mergeable.",
    )
    return "\n".join(lines)


def hostile_record(run: CanaryRun, candidate: dict[str, str]) -> str:
    summary = run.summaries["hostile-gitlab"]
    lines = _header("GitLab hostile-MR deployment boundary", run, candidate)
    lines += [
        f"- Change request: [change]({summary['change_url']}) from an **unprotected** branch,"
        " closed at cleanup",
        "",
        "## Result",
        "",
        *_table(_step_rows(summary["steps"], _observed_json), ("Check", "Result", "Observed")),
        "",
        "`image_substituted` is recorded, not asserted: in-pipeline image enforcement is not",
        "implemented (SPEC-43), so containment rests on credential withholding and the",
        "out-of-band trust auditor.",
    ]
    lines += _footer(
        run,
        "Scoped pass for the recorded boundary. An MR from an unprotected ref could not obtain"
        " any protected credential, prepare failed closed with every later stage skipped, the"
        " forged publication artifacts went unconsumed, and the trust auditor rejected the"
        ' hostile composition. "Credential isolated" holds only in this hardened-child,'
        " unprotected-ref sense.",
    )
    return "\n".join(lines)


RECORDS: dict[str, tuple[tuple[str, ...], Callable[[CanaryRun, dict[str, str]], str]]] = {
    "record-candidate-canary.md": (("panel-github", "panel-gitlab"), canary_record),
    "record-github-current-image.md": (
        ("lifecycle-github",),
        partial(lifecycle_record, platform="github"),
    ),
    "record-gitlab-current-image.md": (
        ("lifecycle-gitlab",),
        partial(lifecycle_record, platform="gitlab"),
    ),
    "record-gitlab-hostile-mr.md": (("hostile-gitlab",), hostile_record),
}


def render_records(run: CanaryRun) -> dict[str, str]:
    """Render complete evidence for the campaigns the run's summaries cover."""
    try:
        candidate = _require_consistent(run)
        return {
            filename: render(run, candidate)
            for filename, (needs, render) in RECORDS.items()
            if run.summaries.keys() >= set(needs)
        }
    except (KeyError, TypeError, AttributeError) as exc:
        raise RecordError(f"invalid canary summary data: {exc}") from exc


def _notes_span(text: str) -> tuple[int, int] | None:
    """Locate the notes body without treating fenced examples as sections."""
    headings = []
    fence: str | None = None
    generated = False
    offset = 0
    for line in text.splitlines(keepends=True):
        start = offset
        offset += len(line)
        if fence is not None:
            if re.fullmatch(rf" {{0,3}}{fence[0]}{{{len(fence)},}}[ \t]*", line.rstrip("\r\n")):
                fence = None
            continue
        opening = re.match(r"^ {0,3}(`{3,}|~{3,})", line)
        if opening is not None:
            fence = opening.group(1)
            continue
        generated |= line.startswith("> Generated by `scripts/canary_evidence_records.py`")
        heading = re.fullmatch(r" {0,3}##[ \t]+(.+?)(?:[ \t]+#+)?[ \t]*", line.rstrip("\r\n"))
        if heading is not None:
            headings.append((heading.group(1), start, offset))
    titles = [title for title, _, _ in headings]
    if "Operator notes" not in titles and not generated:
        return None
    if (
        titles.count("Operator notes") != 1
        or titles.count("Verdict") != 1
        or titles[-2:] != ["Operator notes", "Verdict"]
    ):
        raise RecordError("missing or ambiguous Operator notes / Verdict boundaries")
    return headings[-2][2], headings[-1][1]


def _record_run_identity(header: str) -> tuple[str, str]:
    runs = re.findall(
        r"^- Candidate Canary run: \[`([^`\r\n]+)`\]\(([^()\r\n]+)\)", header, re.MULTILINE
    )
    if len(runs) != 1:
        raise RecordError("missing or ambiguous Candidate Canary run identity")
    return runs[0]


def _record_release_bindings(header: str) -> tuple[str, ...]:
    bindings = []
    for field, values in release_bindings(header).items():
        if len(values) != 1:
            raise RecordError(f"missing or ambiguous Release-{field} binding")
        bindings.append(values[0])
    return tuple(bindings)


def _preserve_operator_notes(path: Path, rendered: str) -> str:
    try:
        # Decode bytes directly so handwritten line endings survive regeneration.
        existing = path.read_bytes().decode("utf-8")
    except FileNotFoundError:
        return rendered
    except (OSError, UnicodeError) as exc:
        raise RecordError(f"cannot read existing record {path.name}") from exc
    try:
        old_span = _notes_span(existing)
        if old_span is None:
            return rendered
        new_span = _notes_span(rendered)
        assert new_span is not None
        old_header = existing[: old_span[0]]
        new_header = rendered[: new_span[0]]
        old_run_id, old_url = _record_run_identity(old_header)
        new_run_id, new_url = _record_run_identity(new_header)
        if old_run_id != new_run_id:
            # A new run replaces the old observations and operator notes.
            return rendered
        old_bindings = _record_release_bindings(old_header)
        new_bindings = _record_release_bindings(new_header)
        if old_url != new_url or old_bindings != new_bindings:
            raise RecordError("the same run has conflicting URL or release bindings")
        return rendered[: new_span[0]] + existing[slice(*old_span)] + rendered[new_span[1] :]
    except RecordError as exc:
        raise RecordError(f"{path.name}: {exc}") from exc


def _json_value(text: str, label: str, kind: type = dict) -> Any:
    try:
        value = json_loads_no_duplicates(text)
    except ValueError as exc:
        raise RecordError(f"{label} is not valid JSON: {exc}") from exc
    if not isinstance(value, kind):
        raise RecordError(f"{label} must be a JSON {'object' if kind is dict else 'array'}")
    return value


def _require_successful_job(job: dict[str, Any]) -> None:
    if job.get("status") != "completed" or job.get("conclusion") != "success":
        raise RecordError(
            f"{job['name']} has status {job.get('status')!r}, "
            f"concluded {job.get('conclusion')!r}; expected completed success"
        )


def _expected_summaries(jobs: list[dict[str, Any]]) -> frozenset[str]:
    expected = set()
    for family in dict.fromkeys(artifact.job for artifact in DEMO_ARTIFACTS.values()):
        artifacts = {key: spec for key, spec in DEMO_ARTIFACTS.items() if spec.job == family}
        family_jobs = [
            job for job in jobs if job["name"] == family or job["name"].startswith(f"{family} (")
        ]
        # GitHub evaluates the campaign condition before expanding its matrix.
        if (
            len(family_jobs) == 1
            and family_jobs[0]["name"] == family
            and family_jobs[0].get("status") == "completed"
            and family_jobs[0].get("conclusion") == "skipped"
        ):
            continue
        if len(family_jobs) != len(artifacts):
            raise RecordError(f"{family} job metadata is missing or ambiguous")
        for key in artifacts:
            pattern = (
                family
                if len(artifacts) == 1
                else rf"{family} \({key.partition('-')[2]}(?:, [^()]+)?\)"
            )
            matches = [job for job in family_jobs if re.fullmatch(pattern, job["name"])]
            if len(matches) != 1:
                raise RecordError(f"{key} job metadata is missing or ambiguous")
            _require_successful_job(matches[0])
            expected.add(key)
    if not expected:
        raise RecordError("the run included no successful canary campaigns")
    return frozenset(expected)


def _artifact_inventory(run_id: str, expected: frozenset[str]) -> dict[int, tuple[str, bool]]:
    response = release_common.gh(
        "api",
        "--hostname",
        "github.com",
        "--paginate",
        "--slurp",
        f"repos/{REPOSITORY}/actions/runs/{run_id}/artifacts?per_page=100",
        error_type=RecordError,
    )
    pages = _json_value(response, "artifact metadata", list)
    if not pages:
        raise RecordError("artifact metadata must contain a nonempty list of pages")
    inventory: dict[int, tuple[str, bool]] = {}
    total_count = None
    for page in pages:
        if not isinstance(page, dict):
            raise RecordError("artifact metadata page must be a JSON object")
        count = page.get("total_count")
        artifacts = page.get("artifacts")
        if type(count) is not int or count < 0 or not isinstance(artifacts, list):
            raise RecordError("artifact metadata page requires total_count and an artifacts list")
        if total_count is not None and count != total_count:
            raise RecordError("artifact metadata pages disagree on total_count")
        total_count = count
        for artifact in artifacts:
            if not isinstance(artifact, dict):
                raise RecordError("artifact metadata entry must be a JSON object")
            artifact_id = artifact.get("id")
            name = artifact.get("name")
            expired = artifact.get("expired")
            if (
                type(artifact_id) is not int
                or artifact_id <= 0
                or not isinstance(name, str)
                or not name
                or type(expired) is not bool
            ):
                raise RecordError(
                    "artifact metadata entry requires a valid ID, name, and expired flag"
                )
            if artifact_id in inventory:
                raise RecordError(f"artifact metadata repeats artifact ID {artifact_id}")
            inventory[artifact_id] = (name, expired)
    if len(inventory) != total_count:
        raise RecordError("artifact metadata is incomplete: entry count differs from total_count")
    for key, artifact in DEMO_ARTIFACTS.items():
        ids = sorted(
            artifact_id for artifact_id, (name, _) in inventory.items() if name == artifact.name
        )
        if key not in expected:
            if ids:
                raise RecordError(f"{key} uploaded an artifact despite its campaign being skipped")
            continue
        # gh run download discards duplicate names, including summaries from earlier attempts.
        # Count expired entries too: their presence still leaves the attempt binding ambiguous.
        if len(ids) != 1:
            raise RecordError(
                f"{artifact.name} requires exactly one artifact; found {len(ids)} (IDs: {ids}). "
                "Dispatch a fresh Candidate Canary run with a new run ID."
            )
        if inventory[ids[0]][1]:
            raise RecordError(
                f"{artifact.name} artifact {ids[0]} has expired. "
                "Dispatch a fresh Candidate Canary run with a new run ID."
            )
    return inventory


def load_run(run_id: str, workdir: Path) -> CanaryRun:
    repository = f"github.com/{REPOSITORY}"
    meta = _json_value(
        release_common.gh(
            "run",
            "view",
            run_id,
            "--repo",
            repository,
            "--json",
            RUN_FIELDS,
            error_type=RecordError,
        ),
        "run metadata",
    )
    required = {
        "conclusion": "success",
        "status": "completed",
        "event": "workflow_dispatch",
        "headBranch": SOURCE_REF.removeprefix("refs/heads/"),
    }
    for field, value in required.items():
        if meta.get(field) != value:
            raise RecordError(f"run {run_id} {field} is {meta.get(field)!r}; expected {value!r}")
    for field in ("url", "createdAt"):
        if not isinstance(meta.get(field), str) or not meta[field]:
            raise RecordError(f"run metadata is missing {field}")
    workflow_id = meta.get("workflowDatabaseId")
    if type(workflow_id) is not int or workflow_id <= 0:
        raise RecordError("run metadata is missing a valid workflowDatabaseId")
    workflow = _json_value(
        release_common.gh(
            "api",
            "--hostname",
            "github.com",
            f"repos/{REPOSITORY}/actions/workflows/{workflow_id}",
            error_type=RecordError,
        ),
        "workflow metadata",
    )
    if workflow.get("id") != workflow_id or workflow.get("path") != CANARY_WORKFLOW:
        raise RecordError(f"run {run_id} is not the canonical {CANARY_WORKFLOW} workflow")
    jobs = meta.get("jobs")
    if not isinstance(jobs, list) or not all(
        isinstance(job, dict) and isinstance(job.get("name"), str) for job in jobs
    ):
        raise RecordError("run metadata is missing a valid jobs list")
    verify = [job for job in jobs if job["name"] == "verify-candidate"]
    if len(verify) != 1:
        raise RecordError("verify-candidate job metadata is missing or ambiguous")
    _require_successful_job(verify[0])
    expected = _expected_summaries(jobs)
    inventory = _artifact_inventory(run_id, expected)
    release_common.gh(
        "run",
        "download",
        run_id,
        "--repo",
        repository,
        "--dir",
        str(workdir),
        error_type=RecordError,
    )
    if _artifact_inventory(run_id, expected) != inventory:
        raise RecordError("artifact metadata changed during download; retry release preparation")
    summaries = {}
    for key, artifact in DEMO_ARTIFACTS.items():
        directory = workdir / artifact.name
        if key not in expected:
            if directory.exists():
                raise RecordError(f"{key} uploaded an artifact despite its campaign being skipped")
            continue
        files = list(directory.glob("*.json"))
        if len(files) != 1:
            raise RecordError(f"{key} requires exactly one summary JSON file; found {len(files)}")
        try:
            summaries[key] = _json_value(files[0].read_text(encoding="utf-8"), f"{key} summary")
        except (OSError, UnicodeError) as exc:
            raise RecordError(f"cannot read {key} summary: {exc}") from exc
    findings, scanned, _ = scan([workdir])
    if findings:
        raise RecordError(f"the leak scan flagged the summaries: {sorted(findings)}")
    return CanaryRun(
        run_id=run_id,
        url=meta["url"],
        date=meta["createdAt"][:10],
        summaries=summaries,
        scanned_files=scanned,
    )


def preserve_record_notes(records: dict[str, str], directory: Path) -> dict[str, str]:
    """Render and preflight every generated record before the caller writes any."""
    return {
        name: _preserve_operator_notes(directory / name, text) for name, text in records.items()
    }
